// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYk8aAGs92-ErIjaBk39bvZmi_aXMTKw',
    appId: '1:911682764483:web:62d2abcf5c401320a56c76',
    messagingSenderId: '911682764483',
    projectId: 'cookandboo',
    authDomain: 'cookandboo.firebaseapp.com',
    storageBucket: 'cookandboo.firebasestorage.app',
    measurementId: 'G-K0VY4E4466',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUOUJqV6mkQ4AykwMa15fM_tXgS9cTxk',
    appId: '1:911682764483:android:f37c432e9cbcc77da56c76',
    messagingSenderId: '911682764483',
    projectId: 'cookandboo',
    storageBucket: 'cookandboo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDizy_U-86x_j0TwcJ7eTYejTbIfkEreAU',
    appId: '1:911682764483:ios:34dd6ddca0ee6f54a56c76',
    messagingSenderId: '911682764483',
    projectId: 'cookandboo',
    storageBucket: 'cookandboo.firebasestorage.app',
    iosBundleId: 'com.example.cookBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDizy_U-86x_j0TwcJ7eTYejTbIfkEreAU',
    appId: '1:911682764483:ios:34dd6ddca0ee6f54a56c76',
    messagingSenderId: '911682764483',
    projectId: 'cookandboo',
    storageBucket: 'cookandboo.firebasestorage.app',
    iosBundleId: 'com.example.cookBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsYk8aAGs92-ErIjaBk39bvZmi_aXMTKw',
    appId: '1:911682764483:web:bf8d68755ead268ba56c76',
    messagingSenderId: '911682764483',
    projectId: 'cookandboo',
    authDomain: 'cookandboo.firebaseapp.com',
    storageBucket: 'cookandboo.firebasestorage.app',
    measurementId: 'G-3VGF8J58SQ',
  );
}
